apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: {{ .Release.Namespace }}
spec:
  cephVersion:
    image: "ceph/ceph:{{ .Values.cephVersion }}"
  dataDirHostPath: /var/lib/rook
  mon:
    count: 3
  dashboard:
    enabled: true
  storage:
    nodes:
      - name: rke-worker-0
      - name: rke-worker-1
      - name: rke-worker-2
    deviceFilter: sdb
