apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gcp-cluster-issuer
spec:
  acme:
    email: michael@parker.gg
    server: {{ .Values.acmeServer | quote }}
    privateKeySecretRef:
      name: gcp-cluster-issuer-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: {{ .Values.gcpProject }}
            serviceAccountSecretRef:
              name: {{ .Values.serviceAccountSecret }}
              key: {{ .Values.serviceAccountSecretKey }}
